# Generated by Django 4.0.1 on 2022-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='about',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
