# Generated by Django 4.0.1 on 2022-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blog.IpModel'),
        ),
    ]
