# Generated by Django 4.0.2 on 2022-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_specification_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Specification',
            field=models.TextField(max_length=250),
        ),
    ]
