# Generated by Django 4.0.2 on 2022-02-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='start',
            new_name='star',
        ),
    ]
