# Generated by Django 4.0.2 on 2022-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_start_reviews_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='star',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Trash'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - Watchable'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Perfect'), (10, '10 - Master Piece')], null=True),
        ),
    ]
